{% set version = '4.1.0.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-openxlsx
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/openxlsx_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/openxlsx/openxlsx_{{ version }}.tar.gz
  sha256: 8b7011debe14714de035ef42797c8caa923162d5dc3cc3c2a299fc10eff3d4d1

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-rcpp
    - r-zip
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rcpp
    - r-zip

test:
  commands:
    - $R -e "library('openxlsx')"           # [not win]
    - "\"%R%\" -e \"library('openxlsx')\""  # [win]

about:
  home: https://github.com/awalker89/openxlsx
  license: MIT
  summary: Simplifies the creation of Excel .xlsx files by providing a high level interface to
    writing, styling and editing worksheets. Through the use of 'Rcpp', read/write times
    are comparable to the 'xlsx' and 'XLConnect' packages with the added benefit of
    removing the dependency on Java.
  license_family: MIT

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: openxlsx
# Type: Package
# Title: Read, Write and Edit XLSX Files
# Version: 4.1.0.1
# Date: 2018-05-26
# Authors@R: c( person("Alexander", "Walker", email = "Alexander.Walker1989@gmail.com", role = c("aut", "cre")), person("Luca", "Braglia", role = "ctb"))
# URL: https://github.com/awalker89/openxlsx
# BugReports: https://github.com/awalker89/openxlsx/issues
# Maintainer: ORPHANED
# Description: Simplifies the creation of Excel .xlsx files by providing a high level interface to writing, styling and editing worksheets. Through the use of 'Rcpp', read/write times are comparable to the 'xlsx' and 'XLConnect' packages with the added benefit of removing the dependency on Java.
# License: MIT + file LICENSE
# LinkingTo: Rcpp
# Encoding: UTF-8
# Depends: R (>= 3.3.0)
# Imports: methods, Rcpp, grDevices, stats, utils, zip
# VignetteBuilder: knitr
# Suggests: knitr, testthat
# RoxygenNote: 6.0.1.9000
# Collate: 'CommentClass.R' 'HyperlinkClass.R' 'RcppExports.R' 'class_definitions.R' 'StyleClass.R' 'WorkbookClass.R' 'baseXML.R' 'borderFunctions.R' 'chartsheet_class.R' 'conditional_formatting.R' 'helperFunctions.R' 'loadWorkbook.R' 'onUnload.R' 'openXL.R' 'openxlsx.R' 'openxlsxCoerce.R' 'readWorkbook.R' 'sheet_data_class.R' 'workbook_column_widths.R' 'workbook_read_workbook.R' 'workbook_write_data.R' 'worksheet_class.R' 'wrappers.R' 'writeData.R' 'writeDataTable.R' 'writexlsx.R'
# NeedsCompilation: yes
# Packaged: 2019-05-28 09:03:00 UTC; ripley
# Author: Alexander Walker [aut, cre], Luca Braglia [ctb]
# Repository: CRAN
# Date/Publication: 2019-05-28 22:10:36
# X-CRAN-Original-Maintainer: Alexander Walker <Alexander.Walker1989@gmail.com>
# X-CRAN-Comment: Orpahaned and corrected on 2019-05-28 as check issues were not addressed despite reminder.
