travis:
  secure:
    BINSTAR_TOKEN: UwWBNCskgfE1iP5PhjBue6An3GWqAY20OHJCFDpcOS1MrjlFyEH4StRQ0hdax7vkwPGUCFZT5VP85xrJ2Gqe4h12S1yD7ejw0IVEO8vuO/rBlhF1w/GP3R0bFn9cMeuB9dtuJMaB3AT/+GYY/x1o+pqd6a955BpMGLFa/7e/2AtHF3aaSHMhXxXxpIqvIu+cTQYekT8/KfItXzWkJq52Cyx1BlDDjxnjjHKUsnOv+w5dk3zg9jRnYIW1bQzi69Z3CaeNBx5+br/8ZzbGO1tm0oDYEEHzOd8S4wVwVeyw0eaCujrXnqG07yqDKddugnB2vpQg/XbjEQKgXP1lCae+BsRwCwyde6OZ049ieMK0rSG177y05vhAHns4rsLjCQlSQotimY7AKGxu26tuYLjdZHheZIQ/Fj1OgkvmQ+V991taR2TjRaLjcfs8xhuH4AnWdKkDEgGe98PwpM9uGkk2mHZDOukrHklS1JhZzUU4/Kb6R4Z7E/LE2etPyRs27RTmmXjNgLSBv8c0T4ySAHB3ppnS4J4wtkkQHnYFHpCHKnoNR/mhgutlUaqW1SsV3gF/MLrGTehvL0p7CEfPX0vqXUMwlW62s4hfoPNAH6z905sjEXDvHEi0iydhUztOfcU8ccKjMl7iTnU/bySkxpETmVERibfUI6EeQba9nCrZOJQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
