appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default, win: azure}
travis:
  secure: {BINSTAR_TOKEN: CyU2GsNa60MpLO74c2WDZYKDqeIIirKyF9GKN377DOyR6aZXptmuak+XW0FanRMrLCtOBbThkvU6KhH72tOhxYSTxBGdl8+HBy2JrOhNAkNycXbKgYBUgyrzSz/LibI7oEPxTBCaF2rFclM+zvVFccdLeMA1DwDCjYHYJWG8GdHCMipcbNCGofxqMwoMW697A1nTQfSbA3yMEXgk2euQe409gz/+j0GCp/+vzab29k07o4Y6kuVMGgQ56tw7tYuwmXg4IlJHf3QjXVW47de7GXtz5DzVQAYtoqt0COyY6sI2A5isSWD2CqUDRJqb5nabPZzW9nJHexGHYfvi0QC3r6hoeMBui2X/k5bO5XGvYlLLUpaJo8fmkJtb/UImqh9gH6vhjVGYtzvnungAD5yPMLqAx0hM0OKC2BoaZOdAJLu+VlN3K2dn6UZ0tLkiy9QSZhZOTkiUWGYXqrqjB8i9u2JvpwbIfrU4olHx6BG00ugqA8Q25EESh+5Hpdfr7o64/KJa8MwyCQpSuVGOFQ1Z6yTxMyNo70e/mhR/4b4F2KD/P5pDpA1fiQlvSOe9cZeoCH4iX/PehXTNgn5zLdNeHlbzhuOzuXSovbo91TBUHEBpxrjHdnjryqWeF3pPl3w4ZrDCrjPVavqspVdfO7rKPPSyJguQira03gUJI4QevjI=}
bot:
  automerge: true
